PricingRule::GetTwoForOneRule:
  product_code: GR1

PricingRule::BulkDiscountRule:
  product_code: SR1
  minimum_quantity_for_discount: 3
  discounted_price_per_item: 4.50

PricingRule::DiscountRule:
  product_code: CF1
  minimum_quantity_for_discount: 3
  discount_factor: 0.6666666667